"use client";

import { FileText, Loader2, RefreshCw, UploadCloud } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import "../aira-v2.css";
import { AiraV2Frame } from "@/components/AiraV2Frame";

type Asset = { id:string; filename:string; mimeType:string; sizeBytes:number; status:"UPLOADING"|"QUEUED"|"PROCESSING"|"READY"|"FAILED"; errorMessage:string|null; createdAt:string; updatedAt:string };
const bytes = (n:number) => n < 1024 ? `${n} B` : n < 1048576 ? `${(n/1024).toFixed(1)} KB` : `${(n/1048576).toFixed(1)} MB`;

export default function KnowledgePage() {
  const [assets,setAssets]=useState<Asset[]>([]), [loading,setLoading]=useState(true), [uploading,setUploading]=useState(false), [message,setMessage]=useState<string|null>(null);
  const input=useRef<HTMLInputElement>(null);
  const refresh=useCallback(async()=>{ try { const r=await fetch("/api/knowledge/library",{cache:"no-store"}); const d=await r.json() as {assets?:Asset[];error?:{message?:string}}; if(!r.ok) throw new Error(d.error?.message??"Knowledge workspace unavailable."); setAssets(d.assets??[]); setMessage(null); } catch(e){setMessage(e instanceof Error?e.message:"Could not load knowledge assets.");} finally{setLoading(false);} },[]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{if(!assets.some(a=>["UPLOADING","QUEUED","PROCESSING"].includes(a.status)))return;const t=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(t);},[assets,refresh]);
  async function upload(file:File){setUploading(true);setMessage(null);try{const form=new FormData();form.set("file",file);const r=await fetch("/api/knowledge",{method:"POST",body:form});const d=await r.json() as {error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??"Upload failed.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.");}finally{setUploading(false);if(input.current)input.current.value="";}}

  return <div className="aira-v2-page"><AiraV2Frame><main className="min-h-[calc(100dvh-58px)] bg-[#0a0c0f] px-5 py-7 md:px-8"><div className="mx-auto max-w-6xl">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#a98b43]">Knowledge</p><h1 className="text-2xl font-semibold tracking-[-.025em] text-[#f2f2ee] md:text-3xl">Files that AIRA can actually use</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8b9098]">Upload documents into AIRA's ingestion queue. READY assets participate in semantic knowledge retrieval during research.</p></div><button onClick={()=>void refresh()} className="inline-flex items-center gap-2 rounded-lg border border-white/[.08] bg-[#111419] px-3 py-2 text-xs text-[#abb0b7]"><RefreshCw className="size-3.5"/>Refresh</button></div>
    <section className="mb-5 rounded-2xl border border-dashed border-white/[.12] bg-[#0f1216] p-7 text-center"><UploadCloud className="mx-auto size-6 text-[#d0b25c]"/><h2 className="mt-3 text-base font-semibold text-[#efefeb]">Add knowledge</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#7d828a]">PDF, DOCX, Markdown, text, CSV, JSON and common images up to 20 MB.</p><input ref={input} type="file" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><button disabled={uploading} onClick={()=>input.current?.click()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#d0ae55] px-4 py-2.5 text-sm font-semibold text-[#111214] disabled:opacity-40">{uploading?<Loader2 className="size-4 animate-spin"/>:<UploadCloud className="size-4"/>}Choose file</button></section>
    {message?<div className="mb-5 rounded-xl border border-amber-300/15 bg-amber-300/[.05] px-4 py-3 text-sm text-amber-100">{message}</div>:null}
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#0f1216]"><div className="border-b border-white/[.07] px-5 py-4"><h2 className="text-sm font-semibold text-[#ededeb]">Library</h2><p className="mt-1 text-xs text-[#72777f]">{assets.length} assets</p></div>{loading?<div className="grid place-items-center py-16"><Loader2 className="size-5 animate-spin text-[#9a8142]"/></div>:assets.length?<ul className="divide-y divide-white/[.06]">{assets.map(a=><li key={a.id} className="flex flex-wrap items-center gap-4 px-5 py-4"><span className="grid size-10 place-items-center rounded-xl bg-[#171a1f] text-[#9ca1a8]"><FileText className="size-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[#e8e9e6]">{a.filename}</p><p className="mt-1 text-xs text-[#6e737b]">{a.mimeType} · {bytes(a.sizeBytes)}</p>{a.errorMessage?<p className="mt-1 text-xs text-red-300">{a.errorMessage}</p>:null}</div><span className={`rounded-full border px-2.5 py-1 text-[11px] font-medium ${a.status==="READY"?"border-emerald-400/20 text-emerald-300":a.status==="FAILED"?"border-red-400/20 text-red-300":"border-[#c9a84c]/20 text-[#d1b35d]"}`}>{a.status}</span></li>)}</ul>:<div className="py-16 text-center text-sm text-[#686d75]">No knowledge assets yet.</div>}</section>
  </div></main></AiraV2Frame></div>;
}
