import { clipboard, shell } from 'electron'
import { promises as fs } from 'fs'
import os from 'os'
import path from 'path'
import { logAudit } from './audit'
import { androidDevices, androidLaunch, androidPull, androidPush, androidScreenshot, androidShell, androidStatus, androidSwipe, androidTap, androidText } from './android'
import { browser } from './browser'
import { getSettings } from './config'
import { focusWindow, launchApp, listWindows, mouseClick, pasteText, powerShell, pressKeys, scroll } from './computer'
import { addMemory, searchMemory } from './memory'
import { resolvePathInsideRoot } from './policy'
import { indexWorkspace, ragStatus, searchWorkspace } from './rag'
import { analyzeScreen, capturePrimaryScreen, locateOnScreen } from './screen'
import { cancelTask, createTask, listTasks } from './scheduler'
import { getSkill, installSkillFromFile, listSkills, removeSkill } from './skills'
import type { ToolContext, ToolDescriptor } from './types'
interface ToolSpec extends ToolDescriptor { run:(args:Record<string,unknown>,context:ToolContext)=>Promise<unknown> }
function safePath(input:string):string{const root=path.resolve(getSettings().workspaceRoot);const expanded=input.startsWith('~')?path.join(os.homedir(),input.slice(1)):input;const target=path.isAbsolute(expanded)?path.resolve(expanded):path.resolve(root,expanded||'.');return resolvePathInsideRoot(root,target)}
function asString(value:unknown,max=20_000):string{return String(value??'').slice(0,max)}
function requireCapability(enabled:boolean,name:string):void{if(!enabled)throw new Error(`${name} is disabled in Settings.`)}
const tools:Record<string,ToolSpec>={
system_info:{name:'system_info',description:'Get OS, CPU, RAM, hostname, uptime and current time.',requiresApproval:false,risk:'low',async run(){return{platform:os.platform(),release:os.release(),arch:os.arch(),hostname:os.hostname(),cpu:os.cpus()[0]?.model,cores:os.cpus().length,totalMemoryGB:+(os.totalmem()/1024**3).toFixed(1),freeMemoryGB:+(os.freemem()/1024**3).toFixed(1),uptimeHours:+(os.uptime()/3600).toFixed(1),time:new Date().toString()}}},
list_directory:{name:'list_directory',description:'List files/folders inside workspace. Args: path.',requiresApproval:false,risk:'low',async run(args){const target=safePath(asString(args.path,2000));const items=await fs.readdir(target,{withFileTypes:true});return items.slice(0,300).map(item=>({name:item.name,type:item.isDirectory()?'dir':'file'}))}},
read_file:{name:'read_file',description:'Read UTF-8 file inside workspace. Args: path.',requiresApproval:false,risk:'low',async run(args){const target=safePath(asString(args.path,2000));const stat=await fs.stat(target);if(stat.size>2_000_000)throw new Error('File exceeds 2 MB read limit.');return await fs.readFile(target,'utf8')}},
write_file:{name:'write_file',description:'Write UTF-8 file inside workspace. Args: path, content.',requiresApproval:true,risk:'medium',async run(args){const target=safePath(asString(args.path,2000));await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,asString(args.content,1_000_000),'utf8');return{written:target}}},
create_directory:{name:'create_directory',description:'Create folder inside workspace. Args: path.',requiresApproval:true,risk:'medium',async run(args){const target=safePath(asString(args.path,2000));await fs.mkdir(target,{recursive:true});return{created:target}}},
delete_path:{name:'delete_path',description:'Delete file/folder inside workspace. Args: path. Destructive.',requiresApproval:true,risk:'high',async run(args){const target=safePath(asString(args.path,2000));if(target===path.resolve(getSettings().workspaceRoot))throw new Error('Cannot delete workspace root.');await fs.rm(target,{recursive:true,force:false});return{deleted:target}}},
run_powershell:{name:'run_powershell',description:'Run PowerShell command with 60s timeout. Args: command.',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');const command=asString(args.command,20_000).trim();if(!command)throw new Error('Missing PowerShell command.');return await powerShell(command)}},
launch_app:{name:'launch_app',description:'Launch installed application/executable. Args: target.',requiresApproval:true,risk:'medium',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{launched:await launchApp(asString(args.target,1000)),target:asString(args.target,1000)}}},
list_windows:{name:'list_windows',description:'List visible desktop windows and titles.',requiresApproval:false,risk:'low',async run(){requireCapability(getSettings().computerControlEnabled,'Computer control');return await listWindows()}},
focus_window:{name:'focus_window',description:'Bring a desktop window to foreground by title/process query. Args: query.',requiresApproval:true,risk:'medium',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{focused:await focusWindow(asString(args.query,300))}}},
mouse_click:{name:'mouse_click',description:'Click absolute screen coordinates. Args: x, y, button(left/right).',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{clicked:await mouseClick(Number(args.x),Number(args.y),args.button==='right'?'right':'left')}}},
type_text:{name:'type_text',description:'Paste text into the currently focused app. Args: text.',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{typed:await pasteText(asString(args.text,20_000))}}},
press_keys:{name:'press_keys',description:'Press common keyboard key/chord. Args: keys.',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{pressed:await pressKeys(asString(args.keys,100))}}},
scroll:{name:'scroll',description:'Scroll active desktop app. Args: delta.',requiresApproval:true,risk:'medium',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return{scrolled:await scroll(Number(args.delta)||-720)}}},
open_url:{name:'open_url',description:'Open HTTP(S) URL in default browser. Args: url.',requiresApproval:false,risk:'low',async run(args){const url=asString(args.url,4000);if(!/^https?:\/\//i.test(url))throw new Error('Only HTTP(S) URLs are allowed.');await shell.openExternal(url);return{opened:url}}},
open_path:{name:'open_path',description:'Open a file/folder inside workspace with default app. Args: path.',requiresApproval:true,risk:'medium',async run(args){const target=safePath(asString(args.path,2000));const error=await shell.openPath(target);if(error)throw new Error(error);return{opened:target}}},
get_clipboard:{name:'get_clipboard',description:'Read current text clipboard.',requiresApproval:false,risk:'low',async run(){return clipboard.readText().slice(0,50_000)}},
set_clipboard:{name:'set_clipboard',description:'Replace clipboard text. Args: text.',requiresApproval:true,risk:'medium',async run(args){clipboard.writeText(asString(args.text,50_000));return{ok:true}}},
remember:{name:'remember',description:'Store durable semantic memory. Args: text, tags(optional array).',requiresApproval:false,risk:'low',async run(args){return await addMemory(getSettings(),asString(args.text,12_000),Array.isArray(args.tags)?args.tags.map(String):[])}},
recall:{name:'recall',description:'Semantic search durable memory. Args: query, limit.',requiresApproval:false,risk:'low',async run(args){return await searchMemory(getSettings(),asString(args.query,4000),Number(args.limit)||8)}},
index_workspace:{name:'index_workspace',description:'Build semantic RAG index for supported text/code files in workspace.',requiresApproval:false,risk:'low',async run(){return await indexWorkspace(getSettings())}},
search_workspace:{name:'search_workspace',description:'Semantic search indexed workspace. Args: query, limit.',requiresApproval:false,risk:'low',async run(args){return await searchWorkspace(getSettings(),asString(args.query,4000),Number(args.limit)||8)}},
rag_status:{name:'rag_status',description:'Get semantic workspace index status.',requiresApproval:false,risk:'low',async run(){return ragStatus()}},
capture_screen:{name:'capture_screen',description:'Capture primary desktop screenshot to private app data.',requiresApproval:true,risk:'medium',async run(){requireCapability(getSettings().computerControlEnabled,'Computer control');return await capturePrimaryScreen()}},
analyze_screen:{name:'analyze_screen',description:'Use local vision model to inspect current desktop. Args: prompt.',requiresApproval:true,risk:'medium',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return await analyzeScreen(getSettings(),asString(args.prompt,4000)||'Describe the screen and actionable UI elements.')}},
locate_on_screen:{name:'locate_on_screen',description:'Use vision model to locate a UI target and return absolute x/y. Args: description.',requiresApproval:true,risk:'medium',async run(args){requireCapability(getSettings().computerControlEnabled,'Computer control');return await locateOnScreen(getSettings(),asString(args.description,2000))}},
android_devices:{name:'android_devices',description:'List Android devices connected through ADB.',requiresApproval:false,risk:'low',async run(){return await androidDevices()}},
android_status:{name:'android_status',description:'Read connected Android model, version, battery and display status.',requiresApproval:false,risk:'low',async run(){return await androidStatus()}},
android_screenshot:{name:'android_screenshot',description:'Capture screenshot from connected Android device.',requiresApproval:true,risk:'medium',async run(){return await androidScreenshot()}},
android_tap:{name:'android_tap',description:'Tap Android screen coordinates through ADB. Args: x,y.',requiresApproval:true,risk:'high',async run(args){return{tapped:await androidTap(Number(args.x),Number(args.y))}}},
android_swipe:{name:'android_swipe',description:'Swipe Android screen through ADB. Args: x1,y1,x2,y2,durationMs.',requiresApproval:true,risk:'high',async run(args){return{swiped:await androidSwipe(Number(args.x1),Number(args.y1),Number(args.x2),Number(args.y2),Number(args.durationMs)||350)}}},
android_text:{name:'android_text',description:'Type text into focused Android input through ADB. Args: text.',requiresApproval:true,risk:'high',async run(args){return{typed:await androidText(asString(args.text,4000))}}},
android_launch:{name:'android_launch',description:'Launch Android application by package name. Args: package.',requiresApproval:true,risk:'high',async run(args){return{launched:await androidLaunch(asString(args.package,300))}}},
android_shell:{name:'android_shell',description:'Run an ADB shell command on connected Android device. Args: command.',requiresApproval:true,risk:'high',async run(args){return await androidShell(asString(args.command,8000))}},
android_push:{name:'android_push',description:'Push workspace file to Android. Args: localPath, remotePath.',requiresApproval:true,risk:'high',async run(args){return{pushed:await androidPush(asString(args.localPath,2000),asString(args.remotePath,2000))}}},
android_pull:{name:'android_pull',description:'Pull Android file into workspace. Args: remotePath, localPath.',requiresApproval:true,risk:'high',async run(args){return{pulled:await androidPull(asString(args.remotePath,2000),asString(args.localPath,2000))}}},
browser_open:{name:'browser_open',description:'Open URL in persistent AIRA browser session. Args: url.',requiresApproval:false,risk:'low',async run(args){requireCapability(getSettings().browserEnabled,'Browser automation');return await browser.open(asString(args.url,4000))}},
browser_snapshot:{name:'browser_snapshot',description:'Read current AIRA browser page text and interactive element refs.',requiresApproval:false,risk:'low',async run(){requireCapability(getSettings().browserEnabled,'Browser automation');return await browser.snapshot()}},
browser_click:{name:'browser_click',description:'Click browser element ref from latest snapshot. Args: ref.',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().browserEnabled,'Browser automation');return{clicked:await browser.click(asString(args.ref,50))}}},
browser_type:{name:'browser_type',description:'Type into browser element ref. Args: ref,text,submit.',requiresApproval:true,risk:'high',async run(args){requireCapability(getSettings().browserEnabled,'Browser automation');return{typed:await browser.type(asString(args.ref,50),asString(args.text,20_000),Boolean(args.submit))}}},
browser_back:{name:'browser_back',description:'Navigate AIRA browser back one page.',requiresApproval:false,risk:'low',async run(){requireCapability(getSettings().browserEnabled,'Browser automation');return{wentBack:await browser.back()}}},
browser_screenshot:{name:'browser_screenshot',description:'Capture AIRA browser page screenshot to private app data.',requiresApproval:true,risk:'medium',async run(){requireCapability(getSettings().browserEnabled,'Browser automation');return await browser.screenshot()}},
browser_close:{name:'browser_close',description:'Close AIRA browser window.',requiresApproval:false,risk:'low',async run(){return{closed:browser.close()}}},
schedule_task:{name:'schedule_task',description:'Create durable scheduled read-only agent task. Args: prompt,runAt or intervalMinutes.',requiresApproval:true,risk:'medium',async run(args){return createTask(asString(args.prompt,10_000),args.runAt?asString(args.runAt,100):undefined,Number(args.intervalMinutes)||undefined)}},
list_tasks:{name:'list_tasks',description:'List scheduled tasks and latest results.',requiresApproval:false,risk:'low',async run(){return listTasks()}},
cancel_task:{name:'cancel_task',description:'Disable scheduled task. Args: id.',requiresApproval:true,risk:'medium',async run(args){return{cancelled:cancelTask(asString(args.id,200))}}},
list_skills:{name:'list_skills',description:'List installed custom AIRA skills.',requiresApproval:false,risk:'low',async run(){return listSkills()}},
install_skill:{name:'install_skill',description:'Install skill JSON from workspace. Args: path.',requiresApproval:true,risk:'medium',async run(args){return await installSkillFromFile(safePath(asString(args.path,2000)))}},
remove_skill:{name:'remove_skill',description:'Remove installed skill. Args: idOrName.',requiresApproval:true,risk:'medium',async run(args){return{removed:removeSkill(asString(args.idOrName,200))}}},
run_skill:{name:'run_skill',description:'Load custom skill instructions into current reasoning loop. Args: name.',requiresApproval:false,risk:'low',async run(args){const skill=getSkill(asString(args.name,200));if(!skill)throw new Error('Skill not found.');return{name:skill.name,instructions:skill.instructions}}}
}
export function toolDescriptors():ToolDescriptor[]{return Object.values(tools).map(({run:_run,...descriptor})=>descriptor)}
export function toolCatalog():string{return toolDescriptors().map(tool=>`- ${tool.name}: ${tool.description}${tool.requiresApproval?` [APPROVAL ${tool.risk.toUpperCase()}]`:''}`).join('\n')}
export async function executeTool(name:string,args:Record<string,unknown>={},context:ToolContext):Promise<unknown>{const spec=tools[name];if(!spec)throw new Error(`Unknown tool: ${name}`);let approved=true;if(spec.requiresApproval){if(context.unattended)approved=false;else approved=await context.approve(`Allow ${name}?`,JSON.stringify(args,null,2).slice(0,5000),spec.risk)}logAudit({type:'tool',tool:name,approved,summary:JSON.stringify(args).slice(0,500)});if(!approved)return{denied:true,reason:context.unattended?'Unattended tasks cannot execute state-changing tools.':'User denied action.'};try{const result=await spec.run(args,context);logAudit({type:'tool_result',tool:name,summary:JSON.stringify(result).slice(0,700)});return result}catch(error){logAudit({type:'tool_error',tool:name,summary:error instanceof Error?error.message:String(error)});throw error}}
