#!/usr/bin/env bash
# Install AIRA's persistent agent-run reconciler on the existing Linux runtime
# host. Run after (or alongside) infra/aira-runtime/bootstrap.sh.

set -Eeuo pipefail

STATE_DIR=/etc/aira
ENV_FILE="$STATE_DIR/reconciler.env"
VERCEL_ENV_FILE="$STATE_DIR/vercel.production.env"
INSTALL_DIR=/usr/local/lib/aira
UNIT_PATH=/etc/systemd/system/aira-reconciler.service
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKER_SOURCE="$REPO_ROOT/infra/aira-runtime/reconciler-worker.sh"
UNIT_SOURCE="$REPO_ROOT/infra/aira-runtime/systemd/aira-reconciler.service"
SERVICE_USER=aira-reconciler

log()  { printf '\033[1;36m[aira]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[aira] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ "${EUID}" -eq 0 ]] || die "Run as root: sudo bash infra/aira-runtime/install-reconciler.sh"
[[ -f "$WORKER_SOURCE" ]] || die "Missing reconciler worker: $WORKER_SOURCE"
[[ -f "$UNIT_SOURCE" ]] || die "Missing systemd unit: $UNIT_SOURCE"
command -v openssl >/dev/null 2>&1 || die "openssl is required"
command -v curl >/dev/null 2>&1 || die "curl is required"
command -v flock >/dev/null 2>&1 || die "flock is required"
command -v systemctl >/dev/null 2>&1 || die "systemd is required"

AIRA_APP_BASE_URL="${AIRA_APP_BASE_URL:-https://aira-ai-live.vercel.app}"
if [[ ! "$AIRA_APP_BASE_URL" =~ ^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?$ ]]; then
  die "AIRA_APP_BASE_URL must be an HTTPS origin without credentials, query, fragment or path"
fi
AIRA_APP_BASE_URL="${AIRA_APP_BASE_URL%/}"

install -d -m 0700 "$STATE_DIR"
install -d -m 0755 "$INSTALL_DIR"

if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --home-dir /nonexistent --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

# Preserve the token across re-runs. Never print it and never pass it in argv.
existing_token=""
if [[ -f "$ENV_FILE" ]]; then
  existing_token="$(sed -n 's/^AIRA_AGENT_RECONCILER_TOKEN=//p' "$ENV_FILE" | head -n 1)"
fi
if [[ -z "$existing_token" ]]; then
  existing_token="$(openssl rand -hex 32)"
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by infra/aira-runtime/install-reconciler.sh. Mode 600. Never commit.
AIRA_APP_BASE_URL=$AIRA_APP_BASE_URL
AIRA_AGENT_RECONCILER_TOKEN=$existing_token
AIRA_RECONCILE_INTERVAL_SECONDS=${AIRA_RECONCILE_INTERVAL_SECONDS:-30}
AIRA_RECONCILE_JITTER_SECONDS=${AIRA_RECONCILE_JITTER_SECONDS:-10}
AIRA_RECONCILE_REQUEST_TIMEOUT_SECONDS=${AIRA_RECONCILE_REQUEST_TIMEOUT_SECONDS:-20}
AIRA_RECONCILE_MAX_BACKOFF_SECONDS=${AIRA_RECONCILE_MAX_BACKOFF_SECONDS:-300}
EOF
chmod 0600 "$ENV_FILE"

install -m 0755 "$WORKER_SOURCE" "$INSTALL_DIR/reconciler-worker.sh"
install -m 0644 "$UNIT_SOURCE" "$UNIT_PATH"

# Add/replace only the one Vercel-side token required by the protected endpoint.
# The value is written to the existing root-only handoff file, never stdout.
touch "$VERCEL_ENV_FILE"
chmod 0600 "$VERCEL_ENV_FILE"
tmp_env="$(mktemp "$STATE_DIR/vercel.production.env.XXXXXX")"
chmod 0600 "$tmp_env"
grep -v '^AIRA_AGENT_RECONCILER_TOKEN=' "$VERCEL_ENV_FILE" > "$tmp_env" || true
printf 'AIRA_AGENT_RECONCILER_TOKEN=%s\n' "$existing_token" >> "$tmp_env"
mv "$tmp_env" "$VERCEL_ENV_FILE"
chmod 0600 "$VERCEL_ENV_FILE"

systemctl daemon-reload
systemctl enable --now aira-reconciler.service >/dev/null

log "Persistent reconciler installed and enabled."
log "AIRA app origin: $AIRA_APP_BASE_URL"
log "Token stored in $ENV_FILE and $VERCEL_ENV_FILE (values not printed)."
log "Apply the Vercel handoff file, redeploy AIRA, then inspect: systemctl status aira-reconciler"
