import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron'
function on(channel:string,callback:(payload:any)=>void):()=>void{const handler=(_event:IpcRendererEvent,payload:any)=>callback(payload);ipcRenderer.on(channel,handler);return()=>ipcRenderer.removeListener(channel,handler)}
const api={
send:(request:unknown)=>ipcRenderer.invoke('agent:send',request),getSettings:()=>ipcRenderer.invoke('settings:get'),setSettings:(patch:unknown)=>ipcRenderer.invoke('settings:set',patch),secretStatus:()=>ipcRenderer.invoke('secrets:status'),setSecret:(key:string,value:string)=>ipcRenderer.invoke('secrets:set',key,value),
ollamaStatus:()=>ipcRenderer.invoke('ollama:status'),compatibleStatus:()=>ipcRenderer.invoke('compatible:status'),pullModel:(model:string)=>ipcRenderer.invoke('ollama:pull',model),
listenOnce:()=>ipcRenderer.invoke('voice:listen'),speak:(text:string)=>ipcRenderer.invoke('voice:speak',text),stopSpeaking:()=>ipcRenderer.invoke('voice:stop-speaking'),startContinuousVoice:()=>ipcRenderer.invoke('voice:start-continuous'),stopContinuousVoice:()=>ipcRenderer.invoke('voice:stop-continuous'),
approve:(id:string,approved:boolean)=>ipcRenderer.invoke('agent:approval-response',id,approved),onApprovalRequest:(callback:(payload:unknown)=>void)=>on('agent:approval-request',callback),onVoiceTranscript:(callback:(payload:unknown)=>void)=>on('voice:transcript',callback),onUpdateStatus:(callback:(payload:unknown)=>void)=>on('update:status',callback),
listMemories:(limit?:number)=>ipcRenderer.invoke('memory:list',limit),deleteMemory:(id:string)=>ipcRenderer.invoke('memory:delete',id),ragStatus:()=>ipcRenderer.invoke('rag:status'),indexWorkspace:()=>ipcRenderer.invoke('rag:index'),listTasks:()=>ipcRenderer.invoke('tasks:list'),listAudit:(limit?:number)=>ipcRenderer.invoke('audit:list',limit),
checkUpdates:()=>ipcRenderer.invoke('update:check'),installUpdate:()=>ipcRenderer.invoke('update:install'),appVersion:()=>ipcRenderer.invoke('app:version')}
contextBridge.exposeInMainWorld('aira',api)
